---
title: "Knapsack Vignette"
author: "Simge Cinar & Hugo Morvan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Loading the necessary library
```{r}
library(knapsack)
library(Rcpp)
```

Generating data
```{r}
RNGversion(min(as.character(getRversion()),"3.5.3"))
set.seed(42, kind = "Mersenne-Twister", normal.kind = "Inversion")
n <- 2000
knapsack_objects <-
  data.frame(
    w=sample(1:4000, size = n, replace = TRUE),
    v=runif(n = n, 0, 10000)
  )
```

# BRUTE FORCE SEARCH

```{r}
x <- knapsack_objects[1:16,]
W <- 3500
```

```{r}
start_time <- Sys.time()
result <- brute_force_knapsack(x,W)
end_time <- Sys.time()
runtime <- end_time - start_time
cat("Runtime:", runtime, "seconds\n")
```

# DYNAMMIC PROGRAMMING

```{r}
x <- knapsack_objects[1:500,]
W <- 3500
```

```{r}
start_time <- Sys.time()
result <- knapsack_dynamic(x = knapsack_objects[1:500,], W = 3500)
end_time <- Sys.time()
runtime <- end_time - start_time
cat("Runtime without rcpp:", runtime, "seconds\n")
```

```{r}
start_time <- Sys.time()
result <- knapsack_dynamic(x = knapsack_objects[1:500,], W = 3500, fast = TRUE)
end_time <- Sys.time()
runtime <- end_time - start_time
cat("Runtime with rcpp:", runtime, "seconds\n")
```

# GREEDY HEURISTIC

```{r}
x <- knapsack_objects[1:1000000,]
W <- 3500
```

```{r}
start_time <- Sys.time()
result <- greedy_knapsack(x,W)
end_time <- Sys.time()
runtime <- end_time - start_time
cat("Runtime:", runtime, "seconds\n")
```




